// Builds design/tokens.css from design/tokens.json (the source). Run: node design/build.mjs
// Apps copy tokens.css (web UIs) or read tokens.json (Rust / native code) and never hard-code a
// value that lives here. See design/DESIGN.md.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const t = JSON.parse(readFileSync(join(here, 'tokens.json'), 'utf8'));

const block = (selector, vars) =>
  `${selector} {\n${Object.entries(vars).map(([k, v]) => `  --ls-${k}: ${v};`).join('\n')}\n}\n`;

// Shared, mode-independent values.
const shared = {
  'font-sans': t.font.sans,
  'font-mono': t.font.mono,
  ...Object.fromEntries(Object.entries(t.type).map(([k, v]) => [`text-${k}`, v])),
  ...Object.fromEntries(Object.entries(t.radius).map(([k, v]) => [`radius-${k}`, v])),
  ...Object.fromEntries(Object.entries(t.space).map(([k, v]) => [`space-${k}`, v])),
  ...Object.fromEntries(Object.entries(t.motion).map(([k, v]) => [`motion-${k}`, v])),
};
for (const [app, { scale }] of Object.entries(t.apps)) {
  for (const [step, hex] of Object.entries(scale)) shared[`${app}-${step}`] = hex;
}

function mode(name) {
  const n = t.neutral[name];
  const g = t.glass[name];
  const vars = Object.fromEntries(Object.entries(n).map(([k, v]) => [k, v]));
  for (const tier of ['1', '2', '3']) {
    vars[`glass-${tier}-bg`] = g[tier].bg;
    vars[`glass-${tier}-filter`] = `blur(${g[tier].blur}) saturate(${g[tier].saturate})`;
  }
  vars['glass-edge'] = g.edge;
  vars['glass-highlight'] = `inset 0 1px 0 ${g.highlight}`;
  vars['glass-shadow'] = g.shadow;
  vars['glass-opaque'] = g.opaque;
  vars['scrim'] = g.scrim;
  vars['aurora-strength'] = g.aurora;
  return vars;
}

// The app's signature color: `data-app="<app>"` on the root picks it.
function appVars(app, modeName) {
  const s = t.apps[app].scale;
  const dark = modeName === 'dark';
  return {
    accent: s[t.accentStep[modeName]],
    'accent-hover': dark ? s['300'] : s['700'],
    'accent-text': dark ? s['300'] : s['700'],
    'accent-soft': dark ? `color-mix(in srgb, ${s['400']} 18%, transparent)` : `color-mix(in srgb, ${s['600']} 14%, transparent)`,
    'accent-ring': dark ? `color-mix(in srgb, ${s['300']} 60%, transparent)` : `color-mix(in srgb, ${s['600']} 50%, transparent)`,
    'aurora-a': s['400'],
    'aurora-b': s[dark ? '700' : '200'],
  };
}

let css = `/* lsuite design system — generated by design/build.mjs from design/tokens.json. Do not edit. */\n\n`;
css += block(':root', shared) + '\n';
css += block(':root, [data-mode="dark"]', mode('dark')) + '\n';
css += block('[data-mode="light"]', mode('light')) + '\n';
css += `@media (prefers-color-scheme: light) {\n${block('  :root:not([data-mode="dark"])', mode('light')).replace(/^/gm, '  ').trimEnd()}\n}\n\n`;
for (const app of Object.keys(t.apps)) {
  css += block(`[data-app="${app}"], [data-app="${app}"][data-mode="dark"]`, appVars(app, 'dark'));
  css += block(`[data-app="${app}"][data-mode="light"]`, appVars(app, 'light'));
  css += `@media (prefers-color-scheme: light) {\n${block(`  [data-app="${app}"]:not([data-mode="dark"])`, appVars(app, 'light')).replace(/^/gm, '  ').trimEnd()}\n}\n\n`;
}

// The three glass tiers as classes, and the window backdrop that gives glass something to blur.
css += `.ls-glass-1, .ls-glass-2, .ls-glass-3 {
  border: 1px solid var(--ls-glass-edge);
  box-shadow: var(--ls-glass-highlight), var(--ls-glass-shadow);
}
.ls-glass-1 { background: var(--ls-glass-1-bg); backdrop-filter: var(--ls-glass-1-filter); -webkit-backdrop-filter: var(--ls-glass-1-filter); }
.ls-glass-2 { background: var(--ls-glass-2-bg); backdrop-filter: var(--ls-glass-2-filter); -webkit-backdrop-filter: var(--ls-glass-2-filter); }
.ls-glass-3 { background: var(--ls-glass-3-bg); backdrop-filter: var(--ls-glass-3-filter); -webkit-backdrop-filter: var(--ls-glass-3-filter); }
.ls-backdrop {
  background-color: var(--ls-bg);
  background-image:
    radial-gradient(60% 50% at 12% 0%, color-mix(in srgb, var(--ls-aurora-a, #888) calc(var(--ls-aurora-strength) * 100%), transparent), transparent 70%),
    radial-gradient(50% 45% at 92% 100%, color-mix(in srgb, var(--ls-aurora-b, #666) calc(var(--ls-aurora-strength) * 100%), transparent), transparent 70%);
}
@media (prefers-reduced-transparency: reduce) {
  .ls-glass-1, .ls-glass-2, .ls-glass-3 { background: var(--ls-glass-opaque); backdrop-filter: none; -webkit-backdrop-filter: none; }
}
@supports not ((backdrop-filter: blur(1px)) or (-webkit-backdrop-filter: blur(1px))) {
  .ls-glass-1, .ls-glass-2, .ls-glass-3 { background: var(--ls-glass-opaque); }
}
`;

writeFileSync(join(here, 'tokens.css'), css);
console.log(`design/tokens.css: ${css.length} bytes`);
