// Builds design/tokens.css from design/tokens.json (the source). Run: node design/build.mjs
// Apps copy tokens.css (web UIs) or read tokens.json (Rust / native code) and never hard-code a
// value that lives here. See design/DESIGN.md.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const t = JSON.parse(readFileSync(join(here, 'tokens.json'), 'utf8'));

const block = (selector, vars) =>
  `${selector} {\n${Object.entries(vars).map(([k, v]) => `  --ls-${k}: ${v};`).join('\n')}\n}\n`;

// Shared, mode-independent values.
const shared = {
  'font-sans': t.font.sans,
  'font-mono': t.font.mono,
  ...Object.fromEntries(Object.entries(t.type).map(([k, v]) => [`text-${k}`, v])),
  ...Object.fromEntries(Object.entries(t.radius).map(([k, v]) => [`radius-${k}`, v])),
  ...Object.fromEntries(Object.entries(t.space).map(([k, v]) => [`space-${k}`, v])),
  ...Object.fromEntries(Object.entries(t.motion).map(([k, v]) => [`motion-${k}`, v])),
};
for (const [app, { scale }] of Object.entries(t.apps)) {
  for (const [step, hex] of Object.entries(scale)) shared[`${app}-${step}`] = hex;
}

function mode(name) {
  const n = t.neutral[name];
  const g = t.glass[name];
  const vars = Object.fromEntries(Object.entries(n).map(([k, v]) => [k, v]));
  for (const tier of ['1', '2', '3']) {
    vars[`glass-${tier}-bg`] = g[tier].bg;
    vars[`glass-${tier}-filter`] = `blur(${g[tier].blur}) saturate(${g[tier].saturate})`;
  }
  vars['glass-edge'] = g.edge;
  vars['glass-highlight'] = `inset 0 1px 0 ${g.highlight}`;
  vars['glass-shadow'] = g.shadow;
  vars['glass-opaque'] = g.opaque;
  vars['scrim'] = g.scrim;
  vars['chip-shadow'] = g['chip-shadow'];
  vars['grain-strength'] = g.grain;
  vars['dither-strength'] = g.dither;
  // Film grain and the dot grid of the dithered light, in the mode's ink (data: URIs, no request).
  const ink = name === 'dark' ? '1' : '0';
  vars['grain-image'] = `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='180' height='180'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.85' numOctaves='2' stitchTiles='stitch'/%3E%3CfeColorMatrix values='0 0 0 0 ${ink} 0 0 0 0 ${ink} 0 0 0 0 ${ink} 0 0 0 2.2 -1.15'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E")`;
  vars['dots-image'] = `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='4' height='4'%3E%3Crect width='3' height='3' fill='%23${name === 'dark' ? 'fff' : '000'}'/%3E%3C/svg%3E")`;
  return vars;
}

// v2: every app's interface is black and white, so the accent is the ink of the mode whatever
// the app (`data-app` still names the app; its scale is identity, not interface).
function appVars() {
  return {
    accent: 'var(--ls-ink)',
    'accent-hover': 'color-mix(in srgb, var(--ls-ink) 82%, var(--ls-bg))',
    'accent-text': 'var(--ls-text)',
    'accent-soft': 'color-mix(in srgb, var(--ls-ink) 12%, transparent)',
    'accent-ring': 'color-mix(in srgb, var(--ls-ink) 62%, transparent)',
  };
}

let css = `/* lsuite design system — generated by design/build.mjs from design/tokens.json. Do not edit. */\n\n`;
css += block(':root', shared) + '\n';
css += block(':root, [data-mode="dark"]', mode('dark')) + '\n';
css += block('[data-mode="light"]', mode('light')) + '\n';
css += `@media (prefers-color-scheme: light) {\n${block('  :root:not([data-mode="dark"])', mode('light')).replace(/^/gm, '  ').trimEnd()}\n}\n\n`;
css += block(':root, [data-app]', appVars()) + '\n';

// The three tiers as classes, and the window backdrop: the page colour, two corners of dithered
// light and film grain over all of it.
css += `.ls-glass-1, .ls-glass-2, .ls-glass-3 {
  border: 1px solid var(--ls-glass-edge);
  box-shadow: var(--ls-glass-shadow);
}
.ls-glass-1 { background: var(--ls-glass-1-bg); backdrop-filter: var(--ls-glass-1-filter); -webkit-backdrop-filter: var(--ls-glass-1-filter); }
.ls-glass-2 { background: var(--ls-glass-2-bg); backdrop-filter: var(--ls-glass-2-filter); -webkit-backdrop-filter: var(--ls-glass-2-filter); }
.ls-glass-3 { background: var(--ls-glass-3-bg); backdrop-filter: var(--ls-glass-3-filter); -webkit-backdrop-filter: var(--ls-glass-3-filter); }
.ls-backdrop { background-color: var(--ls-bg); position: relative; isolation: isolate; }
.ls-backdrop::before, .ls-backdrop::after { content: ""; position: absolute; inset: 0; z-index: -1; pointer-events: none; }
.ls-backdrop::before {
  background-image: var(--ls-dots-image), var(--ls-dots-image);
  background-size: 4px 4px;
  opacity: var(--ls-dither-strength);
  -webkit-mask-image: radial-gradient(60% 55% at 0% 0%, #000, transparent 75%), radial-gradient(55% 50% at 100% 100%, #000, transparent 75%);
  mask-image: radial-gradient(60% 55% at 0% 0%, #000, transparent 75%), radial-gradient(55% 50% at 100% 100%, #000, transparent 75%);
}
.ls-backdrop::after { background-image: var(--ls-grain-image); background-size: 180px 180px; opacity: calc(var(--ls-grain-strength) * 2.2); }
@media (prefers-reduced-transparency: reduce) {
  .ls-glass-1, .ls-glass-2, .ls-glass-3 { background: var(--ls-glass-opaque); backdrop-filter: none; -webkit-backdrop-filter: none; }
}
@supports not ((backdrop-filter: blur(1px)) or (-webkit-backdrop-filter: blur(1px))) {
  .ls-glass-1, .ls-glass-2, .ls-glass-3 { background: var(--ls-glass-opaque); }
}
`;

writeFileSync(join(here, 'tokens.css'), css);
console.log(`design/tokens.css: ${css.length} bytes`);
